[package]
name = "inspector-gadget"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = { version = "1.41.1", features = ["full"] }
